
from scrapy import cmdline
import os
os.chdir('spiders')


# cmdline.execute('scrapy crawl canberra_ug'.split())
# cmdline.execute('scrapy crawl canberra_pg'.split())
# cmdline.execute('scrapy crawl westernsydney_ug'.split())
# cmdline.execute('scrapy crawl westernsydney_pg'.split())
# cmdline.execute('scrapy crawl westernsydney_pg_2'.split())
# cmdline.execute('scrapy crawl Queensland_ug'.split())
# cmdline.execute('scrapy crawl Queensland_pg'.split())
# cmdline.execute('scrapy crawl Darwin_ug'.split())
# cmdline.execute('scrapy crawl Darwin_pg'.split())
# cmdline.execute('scrapy crawl Victoria_ug'.split())
# cmdline.execute('scrapy crawl Victoria_pg'.split())
# cmdline.execute('scrapy crawl South_Queensland_ug'.split())
# cmdline.execute('scrapy crawl South_Queensland_pg'.split())
# cmdline.execute('scrapy crawl South_Queensland_pg_2'.split())
# cmdline.execute('scrapy crawl Catholic_ug'.split())
# cmdline.execute('scrapy crawl Catholic_pg'.split())
# cmdline.execute('scrapy crawl Edith_Cowan_ug'.split())
# cmdline.execute('scrapy crawl Edith_Cowan_pg'.split())
# cmdline.execute('scrapy crawl Edith_Cowan_ug'.split())
# cmdline.execute('scrapy crawl Edith_Cowan_pg'.split())
# cmdline.execute('scrapy crawl murdoch_ug'.split())
# cmdline.execute('scrapy crawl murdoch_pg'.split())
# cmdline.execute('scrapy crawl Deakin_ug'.split())
# cmdline.execute('scrapy crawl Deakin_pg'.split())
# cmdline.execute('scrapy crawl Newcastle_ug'.split())
cmdline.execute('scrapy crawl Newcastle_ug_3'.split())
# cmdline.execute('scrapy crawl Newcastle_ug_2'.split())
# cmdline.execute('scrapy crawl Newcastle_pg'.split())
# cmdline.execute('scrapy crawl Newcastle_pg_2'.split())
# cmdline.execute('scrapy crawl deakinBen_ug'.split())
# cmdline.execute('scrapy crawl deakinBen_pg'.split())
# cmdline.execute('scrapy crawl Newcastle_pg_2'.split())
# cmdline.execute('scrapy crawl New_South_Wales_ug'.split())